### ISSUE TITLE
Persist auth token

### ISSUE THREAD

**Issue by poindexter12** [estruyf/homebridge-presence-switch-msgraph#1]
Every time I update settings in the config or reboot the server / container for homebridge, the auth token is lost and it needs to be setup again.

**Comment by estruyf** [comment]
@poindexter12 indeed, the auth token is kept in memory. This is not stored for security reasons, but also I don't restart homebridge or reboot my Raspberry Pi that often. 

We could of course add an option to allow to store it locally by setting a flag.

**Comment by maxb911** [comment]
I'd also be interested in a persistent token. I do restart my homebridge more or less often and then have to do the re-auth again. 

Btw, thanks for your awesome plugin! I'm using it to turn on the light in the Aqara hub that is plugged in in front of my home office door. Works like a charm (when authorized ;) ).

**Comment by luke-rig** [comment]
Hey man, any progress on persistent login token?

**Comment by estruyf** [comment]
@luke-rig no, haven't worked on it yet.

**Comment by redtom13** [comment]
I recognized I need to re-authenticate every time I switch the presence switch, not only on reboot.
Is this expected behavior, or can it be changed.

**Comment by estruyf** [comment]
This is normal, as the access token is not kept for security reasons.

**Comment by estruyf** [comment]
Good news, this has been implemented for `1.5.0`. Please feel free to test out the latest beta by installing it via: `sudo npm i homebridge-presence-switch-msgraph@next -g`

**Comment by luke-rig** [comment]
Works perfectly, no issues here from my tests.

**Comment by estruyf** [comment]
@luke-rig was already fixed. Please try the latest version. I noticed it yesterday myself.

**Comment by luke-rig** [comment]
All working now with that patch!
