### ISSUE TITLE
Can this detect “in a call”?

### ISSUE THREAD

**Issue by luke-rig** [estruyf/homebridge-presence-switch-msgraph#10]
Can this detect “in a call”?

really useful to lower music volume when triggered and return to normal when available

**Comment by estruyf** [comment]
Needs to be checked if that would be a possibility.

**Comment by BobboSA** [comment]
I’ve looked into it before, it is exposed under the same api, I’ll find the methods again in the morning and see if it can perhaps help

**Comment by estruyf** [comment]
I have looked into it and added activity as an option to be able to use it in the service. In order to use it, you need to specify the activity you are interested in, and add it to the `statusColors` object in the config file on Homebridge. By default, you have `available`, `away`, `busy`, `donotdisturb` in there, but you can now add your own custom activity names to be checked.

The available activities are: Available, Away, BeRightBack, Busy, DoNotDisturb, InACall, InAConferenceCall, Inactive, InAMeeting, Offline, OffWork, OutOfOffice, PresenceUnknown, Presenting, UrgentInterruptionsOnly.

Beta version is now available.

**Comment by BobboSA** [comment]
Hi elio, is this implemented in v1.4.1?

**Comment by estruyf** [comment]
This is for `1.5.0`. It has been added only 4 hours ago.

**Comment by BobboSA** [comment]
Awesome, updated and will do some testing and provide feedback, this could be a game changer for me, kids ignore red but may not if it’s flashing indicating an active call in progress :-)

**Comment by estruyf** [comment]
Please feel free to test out the latest beta by installing it via: `sudo npm i homebridge-presence-switch-msgraph@next -g`.

Once I receive positive feedback about it, I can release the next version.

**Comment by estruyf** [comment]
@luke-rig did you also had a chance to test this out? If not, more information can be found here how you can configure it: https://github.com/estruyf/homebridge-presence-switch-msgraph/tree/dev#custom-activity

**Comment by luke-rig** [comment]
All working here as well, added inacall to the config and it turns down my music and turns my lamp red when actived and the opposite when turned off via HomeKit.

One suggestion though is if there can be a UI implementation starting with one switch and add more showing different statuses as people wish. For me I only want a couple, others may want more

**Comment by estruyf** [comment]
@luke-rig can you tell me more about these scenarios? So that I have a good idea of what you want to achieve here?

**Comment by luke-rig** [comment]
Really just after a UI that can add or remove the additional activity types without editing the config.

My use case is that I simply use this plugin to expose my MS teams status into Apple HomeKit. I then setup automations within HomeKit to trigger other devices.

Personally I don’t use the colours that can be set for each status or a number of the status types themselves

**Comment by estruyf** [comment]
Thanks for the feedback @luke-rig. Will create a separate issue for it, and close this one so that this version can be released.

**Comment by BobboSA** [comment]
Can this perhaps be reopened, Although the InACall switch works and activates correctly in Homebridge), the RGB Colours are not passed to the API correctly.

                },
                "InACall": {
                    "red": 0,
                    "green": 200,
                    "blue": 200
                }

Results in the following being submitted to the API -> rgb,*,255,0,0 (Looks like its taken the "busy" RGB values

compared to the following:

                "available": {
                    "red": 0,
                    "green": 255,
                    "blue": 0
                    }

 API ->  rgb,*,0,255,0

**Comment by estruyf** [comment]
@BobboSA thanks for spotting this! The issue has been fixed and is now available in the latest beta version.

**Comment by estruyf** [comment]
Released with `1.5.1`.
