### ISSUE TITLE
Easier activity configuration

### ISSUE THREAD

**Issue by estruyf** [estruyf/homebridge-presence-switch-msgraph#11]
@luke-rig can you tell me more about these scenarios? So that I have a good idea of what you want to achieve here?

_Originally posted by @estruyf in https://github.com/estruyf/homebridge-presence-switch-msgraph/issues/10#issuecomment-765498532_

**Comment by benfysh** [comment]
Without wanting to second guess what @luke-rig wanted when I was working on https://github.com/estruyf/homebridge-presence-switch-msgraph/pull/16 I mocked up the following that shows check boxes to enable the status switches required. They are not in the changes included in that PR as I assume some additional work would be required first.

<img width="601" alt="Screenshot 2021-04-01 at 14 25 40" src="https://user-images.githubusercontent.com/404201/113322177-45827400-930c-11eb-8c33-076e4d2f3b3b.png">

**Comment by estruyf** [comment]
That would be amazing. Would this be possible in Homebridge?

**Comment by estruyf** [comment]
Thanks! I merged your PR and published version `1.6.0`.

**Comment by benfysh** [comment]
Hi @estruyf just to clarify the 'Status Switches' element in that screen shot isn't implemented in that PR just the 'Light details' and 'Status Colours' collapsible sections. I assume that you would need to do something so that they would be an additional config element like`statusColor` is?
