### ISSUE TITLE
Persistant Auth

### ISSUE THREAD

**Issue by BobboSA** [estruyf/homebridge-presence-switch-msgraph#12]
Hi Elio,

I'm getting the following suddenly, I was adding the InACall status, I did 2 reboots and it retained the access token however on the 3rd attempt it seems to have lost it and is not prompting me to re-auth:

[2021/01/25, 13:52:14] [Presence Indicator] Failed to retrieve an accessToken: callback is not a function

**Comment by estruyf** [comment]
Which version are you using?

**Comment by BobboSA** [comment]
Come to think of it, it was fine on the beta 1.5.0 but then I hit update to the “prod” version of 1.5.0 through the hombrige plug-in update option.

**Comment by BobboSA** [comment]
I've just rolled back to the v1.5.0 beta and its working again

[2021/01/25, 19:07:55] [Presence Indicator] Access token acquired.

**Comment by estruyf** [comment]
Thanks! I'll check what could have gone wrong with the merge to the main branch.

**Comment by BobboSA** [comment]
Also there is an issue with the RGB value it’s sending with the InACall status, seems to send the same values as “Busy” (did comment on the closed thread).

**Comment by estruyf** [comment]
Have tried to reproduce the issue for a couple of days, but haven't been able to. I implemented a change that will remove what is in the storage and does the auth again. This should fix the issue. Available in beta.

**Comment by BobboSA** [comment]
And it works!! perfectly! - Will do some testing and let you know if i find anything else. In my setup the "API" server sends the commands to an MQTT broker on the network, from there i have a a few ESP and rPi devices listening and executing actions depending on the status.

**Comment by estruyf** [comment]
Released with `1.5.1`.
