### ISSUE TITLE
Failed to retrieve an accessToken: callback is not a function

### ISSUE THREAD

**Issue by aspaviento** [estruyf/homebridge-presence-switch-msgraph#17]
Dear team, first of all congrats for this amazing plugin. 

After yesterday update (homebridge-presence-switch-msgraph v1.6.0), I am getting this message when trying to enable the plugin from 'Home' app after a reboot of the homebridge installation:

Failed to retrieve an accessToken: callback is not a function

I have a 1.3.4 homebridge, node.js v14.16.0, npm v7.7.6

**Comment by estruyf** [comment]
Should not be related to the latest release, as no code was changed. I think the object cached by Homebridge was not yet using the latest structure.

I just released version 1.6.1 which restarts the auth process on a failure. Let me know if this works.

**Comment by aspaviento** [comment]
Many thanks, now it works. An 'Access token acquired.' message appears in the log indeed.

**Comment by estruyf** [comment]
Thanks for verifying!
