### ISSUE TITLE
Fails to show Authentication Code

### ISSUE THREAD

**Issue by tennr** [estruyf/homebridge-presence-switch-msgraph#18]
Hello,

I've tested the MS Graph and it's working as expected...

{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#users('XX')/presence/$entity",
    "id": "XX",
    "availability": "Available",
    "activity": "Available",
    "outOfOfficeSettings": {
        "message": null,
        "isOutOfOffice": false
    }
}

But the plug-in fails to show the Authentication Code and URL, therefore it is unable to get an accessToken.

[05/04/2021, 18:01:46] [Microsoft Presence Indicator] Failed to retrieve an accessToken: undefined

**Comment by tennr** [comment]
turned on debug... this appears to be tenant related.  We have multiple tenants in our organization, I need to specify which tenant is issuing the token.

error: 'invalid_request',
  error_description: 'AADSTS50059: No tenant-identifying information found in either the request or implied by any provided credentials.\r\n' +

**Comment by estruyf** [comment]
Thanks @tennr for the update! Hope you get this fixed on you tenant.

**Comment by tennr** [comment]
Hi @estruyf ,
There does not appear to be a way to fix this on the AD side.  If the organization has multiple tenants, then the client app needs to provide which tenant should issue the token.  I've worked around the issue by hard-coding the tenant ID onto your MS_LOGIN_URL like this in the Auth.ts code. 

`const MS_LOGIN_URL = "https://login.microsoftonline.com/e90ccfd7-6f87-45a5-a326-c41cba1da82f";`

I'm not well versed in Homebridge plugin structure to read the config file from the Auth.ts code, but I figure something like this would work for the settings.

>     "tenantId": {
>       "title": "Azure AD tenant ID",
>       "description": "The GUID of the Azure AD Directory aka Tenant ID. Use this if your organization has contains multiple tenants, not required if there is only one.",
>       "type": "string",
>       "default": ""
>     },

And then conditionally append it to the login URL

**Comment by estruyf** [comment]
Adding the 'tenantId' as an extra option would a simple fix.

**Comment by estruyf** [comment]
Just published a `1.7.0` beta release. Feel free to give it a try. In this release, you can specify an extra `tenantId` Parameter.

**Comment by tennr** [comment]
> Just published a `1.7.0` beta release. Feel free to give it a try. In this release, you can specify an extra `tenantId` Parameter.

Tested and is working as expected... Thank you!

**Comment by estruyf** [comment]
Thank you for verifying. The new release is now out.
