### ISSUE TITLE
How do we authenticate user?

### ISSUE THREAD

**Issue by rahilp** [estruyf/homebridge-presence-switch-msgraph#31]
I was able to setup the plugin with the app I’d and tenant ID but don’t see an option to login or authenticate as a user?  Am I missing something?

**Comment by estruyf** [comment]
Once set up, you need to turn on the presence switch. On the Homebridge status page, you will see the device login + code in the log output.

![image](https://user-images.githubusercontent.com/2900833/166198066-56d0709a-2439-4060-bf5c-5be916d4c771.png)

Once logged in via the device flow, the plugin will receive an access token and starts to control your light.

**Comment by rahilp** [comment]
Thanks that solves it!
