### ISSUE TITLE
Reset access token

### ISSUE THREAD

**Issue by michaellongden** [estruyf/homebridge-presence-switch-msgraph#40]
Hi 

I had to send admin consent over to our global admin for approval and to get him to approve the link I sent him over the https://microsoft.com/devicelogin URL along with my code but when he approved it, it linked with his account and now it pulls his presence and not my own. 

I have tried uninstalling and reinstalling the plugin but it seems to be cashing the authentication.

**Comment by michaellongden** [comment]
I did try that but is doesn't look to be listed under cashed accessories. Maybe because I am also seeing this issue having not successfully linked it with a device yet:
[09/04/2024, 09:52:58] [Presence Indicator] Seems to be the busy light API was offline

**Comment by estruyf** [comment]
@michaellongden That is unrelated; the MS calls should work even when the API is offline.

It seems that there is no way to remove the persist cache from the UI in homebridge. What you can do is the following:

- Click on the three dots
- Click on terminal
- Delete the persists folder by running the following command: `rm -rf persist`
- Restart homebridge

That did it on my installation.

**Comment by estruyf** [comment]
Just released version `1.8.0` with a new reset button. If you activate it, it will clear the token which should make the process easier of clearing the cached token.

**Comment by michaellongden** [comment]
Perfect, that worked a treat!

**Comment by DennisGaida** [comment]
I love that you created a new version after 3 years @estruyf <3 Still going strong.
