### ISSUE TITLE
Request failure: getaddrinfo EAI_AGAIN graph.microsoft.com

### ISSUE THREAD

**Issue by m3roxx** [estruyf/homebridge-presence-switch-msgraph#5]
I really like your plugin! Many thanks for you effort.

Occasionally, every 1-2 days, I get the following error message:

[Presence Indicator] Something failed while calling the MSGraph
[Presence Indicator] request to https://graph.microsoft.com/beta/me/presence failed, reason: getaddrinfo EAI_AGAIN graph.microsoft.com

which is followed by:

Error: send ENETUNREACH 224.0.0.251:5353
    at doSend (dgram.js:694:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:364:12)
    at afterDns (dgram.js:640:5)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
Error: send ENETUNREACH 224.0.0.251:5353
    at doSend (dgram.js:694:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:364:12)
    at afterDns (dgram.js:640:5)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)

Any suggestions on how to fix this? I assume it could relate to the automatic reconnect of my internet connection. 

The issue is that the presence switch plugin needs to acquire a new access token after these errors so that I need to login to homebridge every or every second day. A persistent auth token, as already requested by someone else, would therefore be a good enhancement in any case.

Happy to discuss!

**Comment by estruyf** [comment]
With the latest version, this should have been fixed. As it ignores the error and tries again the next time. Forgot to close this issue. Thanks for opening it @m3roxx.
