### ISSUE TITLE
Admin consent required for app

### ISSUE THREAD

**Issue by estruyf** [estruyf/homebridge-presence-switch-msgraph#7]
_Originally posted by @Spanishu in https://github.com/estruyf/homebridge-presence-switch-msgraph/issues/6#issuecomment-743977136_

@Spanishu let us continue the discussion here.

**Comment by estruyf** [comment]
@Spanishu would you be able to provide me the URLs and some screenshots?

Just tested it on my end with a reader account and it didn't require admin consent anymore. Is there a message which tells you for what you actually need the admin consent? 

Here the login from the Homebridge app:

![Screenshot 2020-12-13 at 10 30 24](https://user-images.githubusercontent.com/2900833/102008170-ec77db80-3d2e-11eb-9128-bbda760f180e.png)

Here the login from the Presence Light app:

<img width="342" alt="presencelight" src="https://user-images.githubusercontent.com/2900833/102008310-c7379d00-3d2f-11eb-88e1-f325aa0936f5.png">

**Comment by estruyf** [comment]
Same on two other tenants. It could be that your organization specified that apps need to be requested before installed. If that would be the case, it could be that the Presence Light app has already been requested, and therefore able to be used. 

I would suggest requesting the same for the busy-light-serviceapp.

**Comment by Spanishu** [comment]
Hi 

I have clicked the button on Homebridge which gives me the code to launch on microsoft.com/devicelogin
Then I get the screen where to enter my email address 
![image](https://user-images.githubusercontent.com/46416423/102008425-a3c12200-3d30-11eb-9fdb-a4b17e4361b8.png)
Enter the email and password and then I get the Need Admin Approval screen

On the Presencelight when I am asked to authenticate I get to this screen (take a look the URL is different)
![image](https://user-images.githubusercontent.com/46416423/102008494-3eb9fc00-3d31-11eb-9c55-3622fba706dc.png)
Hope this helps!

**Comment by estruyf** [comment]
In that case, it might have been disabled to approve apps yourself. So an admin needs to approve these first. Presence Light is already approved by your organisation, so you'll need to ask to do the same for this app. I'm afraid I cannot do anything.

**Comment by Spanishu** [comment]
I am working on it right now. I will keep you posted!

**Comment by estruyf** [comment]
Cool @Spanishu thanks for the update!

**Comment by Spanishu** [comment]
So, here is what I did and it worked.
- I am using the APPID of my colleague who build the app to run Windows. From what I understand there is less scope in the what is being pulled from Graph.
- I then authenticate with my user, password 

It works like a charm!

**Comment by estruyf** [comment]
Great to hear. About the "less scopes". There cannot be less than what it is right now. As there are only two defined. Standard login and presence read. As you mentioned it is an app from your colleague. It probably means he created the app registration in Microsoft AD, and so it will be approved as it comes from your own domain.

**Comment by Spanishu** [comment]
Super Happy! He mentioned that it requires a scope which requires admin consent. Using his has solved the prob. Would not know what is really happening behind the scenes.

**Comment by estruyf** [comment]
Glad that it's working, closing the issue right now.
