### ISSUE TITLE
startTime & endTime in GMT?

### ISSUE THREAD

**Issue by maxb911** [estruyf/homebridge-presence-switch-msgraph#8]
Are the startTime and endTime flags in GMT? I'm in Germany and therefore on GMT+1. I just noticed, that the offline-switch was on until a couple of minutes ago (9.30am local), while I had the plugin set to 8.30am. Now, past 9.30am, it is reflecting my true status correctly.
Could that be the reason or am I missing something else?  

Thanks,
Max

**Comment by estruyf** [comment]
Hi @maxb911, it uses the current time to what your Raspberry Pi is configured. Set your time based on this.

**Comment by maxb911** [comment]
Hi @estruyf, thanks for your reply. I'm running Homebridge on a Synology Diskstation via Docker. But after what you said, I checked my timezone settings there and it was indeed set to GMT, not GMT+1. That's fixed now and I can use local time with your plugin. So my bad, but thanks for your help and the work you put into this plugin!
