### ISSUE TITLE
Question: reduce poll time

### ISSUE THREAD

**Issue by Spanishu** [estruyf/homebridge-presence-switch-msgraph#9]
Hi

I was wondering if and how I could reduce the poll-time. What would be possible values?

**Comment by raddi** [comment]
Wondering the same!

**Comment by estruyf** [comment]
You can do that by setting the interval property. It defines the time in minutes to check the status.

**Comment by raddi** [comment]
But can you reduce the interval to be lower than 1 minute?

**Comment by estruyf** [comment]
Should work. Can you try by adding 0.5?

**Comment by raddi** [comment]
Tried that already, still exactly 1 minute :/

**Comment by estruyf** [comment]
Just implemented a fix. Version `1.4.1` now makes it possible to lower the value under one minute.

**Comment by raddi** [comment]
Perfect, it works! Thank you very much!

**Comment by nerdherdinc** [comment]
How does one set a time less than a minute? the field only allows integers.

**Comment by timespacedecay** [comment]
> How does one set a time less than a minute? the field only allows integers.

"Plugin Config" does not let you, but you can change the interval to a decimal using "JSON Config" which you get to by clicking the 3 dots on the plugin.
